"use client";

import { useState } from "react";
import { Copy, Check } from "lucide-react";
import type { DemoTask, DemoDecision, DemoRisk, DemoFollowUp } from "@/lib/demo/demo-data";

interface CopyBriefProps {
  title: string;
  summary: string;
  decisions: DemoDecision[];
  tasks: DemoTask[];
  risks: DemoRisk[];
  followUps: DemoFollowUp[];
}

function buildBrief({
  title,
  summary,
  decisions,
  tasks,
  risks,
  followUps,
}: CopyBriefProps): string {
  const openTasks = tasks.filter((t) => t.status !== "DONE");
  const lines: string[] = [
    `# ${title}`,
    ``,
    `## Summary`,
    summary,
    ``,
    `## Decisions (${decisions.length})`,
    ...decisions.map((d) => `- **${d.title}**${d.ownerName ? ` — ${d.ownerName}` : ""}`),
    ``,
    `## Open Tasks (${openTasks.length})`,
    ...openTasks.map(
      (t) => `- [${t.status}] ${t.title}${t.ownerName ? ` · ${t.ownerName}` : ""}${t.deadline ? ` · Due ${t.deadline}` : ""} · ${t.priority}`
    ),
    ``,
    `## Risks (${risks.length})`,
    ...risks.map((r) => `- [${r.severity}] ${r.title}`),
    ``,
    `## Follow-ups (${followUps.filter((f) => !f.completed).length} open)`,
    ...followUps
      .filter((f) => !f.completed)
      .map((f) => `- ${f.title}${f.ownerName ? ` · ${f.ownerName}` : ""}`),
    ``,
    `---`,
    `Generated by Flowstate AI · flowstate.ai`,
  ];
  return lines.join("\n");
}

export function CopyBrief(props: CopyBriefProps) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    const brief = buildBrief(props);
    try {
      await navigator.clipboard.writeText(brief);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const ta = document.createElement("textarea");
      ta.value = brief;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <button
      onClick={handleCopy}
      className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all"
      style={
        copied
          ? {
              background: "rgba(34,197,94,0.12)",
              border: "1px solid rgba(34,197,94,0.32)",
              color: "#86EFAC",
            }
          : {
              background: "rgba(255,255,255,0.045)",
              border: "1px solid rgba(168,140,255,0.16)",
              color: "#F5F4FC",
              backdropFilter: "blur(12px)",
            }
      }
    >
      {copied ? <Check size={14} /> : <Copy size={14} />}
      {copied ? "Copied!" : "Copy execution brief"}
    </button>
  );
}
